"""empty message

Revision ID: b262158f2db4
Revises: None
Create Date: 2016-02-07 16:24:38.876071

"""

# revision identifiers, used by Alembic.
revision = 'b262158f2db4'
down_revision = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biobox',
                    sa.Column('pmid', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('homepage', sa.String(), nullable=True),
                    sa.Column('mailing_list', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('pmid'),
                    sa.UniqueConstraint('title')
                    )
    op.create_table('interface',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('image',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('dockerhub', sa.String(), nullable=False),
                    sa.Column('repo', sa.String(), nullable=False),
                    sa.Column('source', sa.String(), nullable=True),
                    sa.Column('biobox_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['biobox_id'], ['biobox.pmid'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('dockerhub'),
                    sa.UniqueConstraint('repo')
                    )
    op.create_table('task',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('interface_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['interface_id'], ['interface.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('association',
                    sa.Column('biobox_id', sa.Integer(), nullable=True),
                    sa.Column('task_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['biobox_id'], ['biobox.pmid'], ),
                    sa.ForeignKeyConstraint(['task_id'], ['task.id'], )
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('task')
    op.drop_table('image')
    op.drop_table('interface')
    op.drop_table('biobox')
    ### end Alembic commands ###
